### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by adixon** [KarinG/oliverolocal#5]
I've added my favourite colour on the settings page: /admin/appearance/settings/oliverolocal

Now what? I want to do all my work via the web ui!

**Comment by KarinG** [comment]
Did you hit Save Configuration? 😀

<img width="714" alt="image" src="https://user-images.githubusercontent.com/5340555/195896607-26f66a36-b145-4e2a-abd5-9250cce95ca2.png">

**Comment by adixon** [comment]
Sure did, but I didn't set it as my default theme. Duh!
